### PR TITLE
Add fancy boot timeline schema

### PR DESCRIPTION
**Pull request by moul**

### CODE REVIEW

**Comment by moul** [comment]
@QuentinPerez , @brmzkw, @bchatelard, ping for a review

**Comment by QuentinPerez** [comment]
LGTM

**Comment by brmzkw** [comment]
That's awesome!

```
* download kernel in memory
* download initrd in memory
```

I think we should make the distinction here:

* For arm, uboot makes a TFTP request to download the kernel and the initrd
* For x86, the bios makes a TFTP request to get iPXE, then iPXE makes a HTTP request to the metadata API at `http://169.254.42.42/ipxe` to get bootscript details, then it downloads (HTTP again) the kernel kernel/initrd

```
* signal server is "kernel-started" 
```

Since this step is scaleway-specific, I suggest to add details, like:

`* signal server is "kernel-started": make a HTTP request to the metadata API to signal the kernel is started. Useful for debugging purpose: if the boot fails for any reason, you know it failed before/after the kernel started`

And same for 

`* signal server is "booted": make a HTTP request to the metadata API to signal the server is successfully booted. If we don't make this request, the server will be automatically powered off after a few minutes because the boot is considered failed`

**Comment by brmzkw** [comment]
Also, can you explain how do you know it's the first boot in `format ${root} if first boot` ; and how you retrieve the rootfs in `download and extract a rootfs.tar` (URL from a tag?)?

**Comment by moul** [comment]
@brmzkw, fixed

**Comment by brmzkw** [comment]
cool :) lgtm then

**Pull request merged**
