### PR TITLE
Add kexec arm

### PR DESCRIPTION
**Pull request by Firefishy**
Add missing kexec to arm builds to hopefully enable KEXEC_KERNEL / KEXEC_INITRD support for arm.

Confirm builds on arm7l, arm64 untested.

### CODE REVIEW

**Comment by meyskens** [comment]
@QuentinPerez when will this be available to use?

**Comment by QuentinPerez** [comment]
@meyskens tomorrow :)

**Comment by Firefishy** [comment]
:thumbsup: Confirmed working with following tags:
KEXEC_KERNEL=http://mirror.scaleway.com/kernel/armv7l-4.8.3-std-1/uImage-4.8.3-std-1
KEXEC_INITRD=http://mirror.scaleway.com/initrd/initrd-Linux-armv7l-v3.12.3.gz

**Comment by volth** [comment]
Broken again, ```kexec``` not found:

http://i.imgur.com/uIqdiuH.png

**Comment by volth** [comment]
oops, that screen was from ARM64

the screen below is from 32-bit C1.
kexec is broken on both of them, but differently

**Comment by Firefishy** [comment]
Best to open a new bug report.

**Comment by volth** [comment]
It is open already https://github.com/scaleway/initrd/issues/186

**Pull request merged**
